docker:
  host: "${DOCKER_IP:localhost}"

spring:
  main:
    banner-mode: "OFF"
  output:
    ansi.enabled: always
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: "jdbc:postgresql://${database.host}:${database.port}/${database.name}?currentSchema=${database.schema}"
    username: ${database.user}
    password: ${database.password}
    hikari:
      maximum-pool-size: 30
      pool-name: storeroom
      connection-timeout: 500
      idle-timeout: 30000
      minimum-idle: 5
  flyway:
    enabled: true
    locations: classpath:db/migration, classpath:db/dataset

server:
  port: 8000

database:
  port: 5432
  name: "storeroom"
  schema: "storeroom"
