docker:
  host: "${DOCKER_IP:localhost}"

spring:
  profiles:
    active: in-memory
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:db;DB_CLOSE_DELAY=-1"
  flyway:
    enabled: false

database:
  user: "inmemory"
  password: "inmemory"