CREATE TABLE IF NOT EXISTS SHOPPING_LIST_PRODUCTS
(
    ID UUID NOT NULL,
    SHOPPING_LIST_ID UUID NOT NULL,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SHOPPING_LIST_PRODUCTS PRIMARY KEY (ID)
);