CREATE TABLE IF NOT EXISTS STOREROOM_PRODUCT
(
    ID UUID NOT NULL,
    STOREROOM_ID UUID NOT NULL,
    STOCK INT NOT NULL,
    CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_STOREROOM_PRODUCT PRIMARY KEY (ID)
);