CREATE TABLE IF NOT EXISTS STOREROOM
(
    ID UUID NOT NULL,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    OWNER_ID UUID NOT NULL,
    CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_STOREROOM PRIMARY KEY (ID)
);

COMMENT ON COLUMN STOREROOM.ID IS 'Uniquely identifies the storeroom.';
COMMENT ON COLUMN STOREROOM.NAME IS 'Storeroom name.';
COMMENT ON COLUMN STOREROOM.OWNER_ID IS 'Storeroom owner identifier.';
COMMENT ON COLUMN STOREROOM.CREATED_AT IS 'Date time record creation.';
COMMENT ON COLUMN STOREROOM.UPDATED_AT IS 'Date time record modified.';