CREATE TABLE IF NOT EXISTS PRODUCT
(
    ID UUID NOT NULL,
    NAME VARCHAR(255) NOT NULL UNIQUE,
    CREATOR_ID UUID NOT NULL,
    CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (ID)
);

COMMENT ON COLUMN PRODUCT.ID IS 'Uniquely identifies the product.';
COMMENT ON COLUMN PRODUCT.NAME IS 'Product name.';
COMMENT ON COLUMN PRODUCT.CREATOR_ID IS 'Product creator identifier.';
COMMENT ON COLUMN PRODUCT.CREATED_AT IS 'Date time record creation.';
COMMENT ON COLUMN PRODUCT.UPDATED_AT IS 'Date time record modified.';