CREATE TABLE IF NOT EXISTS SHOPPING_LIST
(
    ID UUID NOT NULL,
    STOREROOM_ID UUID NOT NULL,
    OWNER_ID UUID NOT NULL,
    CREATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_SHOPPING_LIST PRIMARY KEY (ID)
);