version: '3.4'

services:
  postgresql:
    image: postgres:12.4
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "storeroom"
