# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Publish to Docker Hub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build --stacktrace
    - name: Publish Docker
      # You may pin to the exact commit or the version.
      # uses: elgohr/Publish-Docker-Github-Action@f7aca2fea76a5218f3c76cd5933c3ba1d8008774
      uses: elgohr/Publish-Docker-Github-Action@3.02
      with:
        # The name of the image you would like to push
        name: storeroom-webapi
        # The login username for the registry
        username: ismaelcabanas14
        # The login password for the registry
        password: ${{ secrets.DOCKER_HUB_PASS }}
        # Use registry for pushing to a custom registry
        registry: # optional
        # Use snapshot to push an additional image
        snapshot: # optional
        # Set the default branch of your repository (default: master)
        default_branch: # optional
        # Use dockerfile when you would like to explicitly build a Dockerfile
        dockerfile: # optional
        # Use workdir when you would like to change the directory for building
        workdir: storeroom-web/
        # Use context when you would like to change the Docker build context.

