# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build and Publish to Docker Hub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build storeroom-webapi with Gradle
      run: ./gradlew build --stacktrace
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_HUB_PASS }} | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin
    - name: Build the Docker image storeroom-webapi
      run: cd storeroom-web/ | docker build -t ismaelcabanas14/storeroom-webapi:latest .
    - name: Push the Docker image to the registry
      run: docker push ismaelcabanas14/storeroom-webapi:latest

